---
# Build definitions for `build.py` - Customized for Docker AMD64 only

# Upstream Framework versions
frameworks:
  jellyfin-web:
    NODEJS_VERSION:
      6c0a64ef12b9eb40a7c4ee4b9d43d0a5f32f2287: 20  # Default
  jellyfin-server:
    DOTNET_VERSION:
      6d1abf67c36379f0b061095619147a3691841e21: 8.0  # Default
      ceb850c77052c465af8422dcf152f1d1d1530457: 9.0

# Docker images - AMD64 only
docker:
  build_function: build_docker
  archmaps:
    amd64:
      DOTNET_ARCH: x64
      IMAGE_ARCH: amd64
      PACKAGE_ARCH: amd64
      QEMU_ARCH: x86_64
      TARGET_ARCH: amd64
  dockerfile: docker/Dockerfile
  # Changed to your custom Docker Hub repository
  imagename: soultaco83/jellyfin_with_request

# Nuget packages (keeping for compatibility but you can remove if not needed)
nuget:
  build_function: build_nuget
  projects:
    - Jellyfin.Data/Jellyfin.Data.csproj
    - MediaBrowser.Common/MediaBrowser.Common.csproj
    - MediaBrowser.Controller/MediaBrowser.Controller.csproj
    - MediaBrowser.Model/MediaBrowser.Model.csproj
    - Emby.Naming/Emby.Naming.csproj
    - src/Jellyfin.Extensions/Jellyfin.Extensions.csproj
    - src/Jellyfin.Database/Jellyfin.Database.Implementations/Jellyfin.Database.Implementations.csproj
    - src/Jellyfin.MediaEncoding.Keyframes/Jellyfin.MediaEncoding.Keyframes.csproj
  feed_urls:
    stable: https://api.nuget.org/v3/index.json
    unstable: https://nuget.pkg.github.com/jellyfin/index.json
