---
# Build definitions for `build.py`

# Docker images
docker:
  build_function: build_docker
  archmaps:
    amd64:
      DOTNET_ARCH: x64
      IMAGE_ARCH: amd64
      PACKAGE_ARCH: amd64
      QEMU_ARCH: x86_64
      TARGET_ARCH: amd64
  dockerfile: docker/Dockerfile
  imagename: soultaco83/jellyfin

# Framework versions configuration
frameworks:
  jellyfin-server:
    DOTNET_VERSION:
      master: "9.0.100"  # Using 8.0 as default for master
      HEAD: "8.0"    # Fallback version

# Nuget packages
nuget:
  build_function: build_nuget
  projects:
    - Jellyfin.Data/Jellyfin.Data.csproj
    - MediaBrowser.Common/MediaBrowser.Common.csproj
    - MediaBrowser.Controller/MediaBrowser.Controller.csproj
    - MediaBrowser.Model/MediaBrowser.Model.csproj
    - Emby.Naming/Emby.Naming.csproj
    - src/Jellyfin.Extensions/Jellyfin.Extensions.csproj
  feed_urls:
    stable: https://api.nuget.org/v3/index.json
    unstable: https://nuget.pkg.github.com/jellyfin/index.json