name: "Release Build and Push to DockerHub"

on:
  schedule:
    # Weekly unstable trigger on Monday at 05:00 GMT
    - cron: '0 3 * * 6'
  workflow_dispatch:
    # Manual trigger from bot
    inputs:
      version:
        required: true
        type: string
        description: 'The server and web stable release tag ("vX.Y.Z") or "master"'

permissions:
  contents: read

jobs:
  Docker:
    runs-on: ubuntu-22.04
    steps:
      - name: "Set version and release type"
        id: version
        run: |
          INPUT_VERSION=${{ inputs.version || 'master' }}
          if [[ "$INPUT_VERSION" == "master" ]]; then
            echo "JELLYFIN_VERSION=$(date +'%Y%m%d%H')" >> $GITHUB_ENV
            echo "JELLYFIN_RELEASE_TYPE=unstable" >> $GITHUB_ENV
          elif [[ "$INPUT_VERSION" =~ ^v[0-9]+ ]]; then
            echo "JELLYFIN_VERSION=$INPUT_VERSION" >> $GITHUB_ENV
            echo "JELLYFIN_RELEASE_TYPE=stable" >> $GITHUB_ENV
          else
            echo "Invalid version input"
            exit 1
          fi
          echo "Input version: $INPUT_VERSION"
          echo "Set JELLYFIN_VERSION: ${{ env.JELLYFIN_VERSION }}"
          echo "Set JELLYFIN_RELEASE_TYPE: ${{ env.JELLYFIN_RELEASE_TYPE }}"

      - name: "Install dependencies"
        run: |-
          sudo apt-get update
          sudo apt-get install --yes python3-git python3-yaml

      - name: "Checkout repository"
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: "Prepare repository"
        run: |-
          ./checkout.py ${{ inputs.version || 'master' }}

      - name: "Run builder for Docker containers"
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
        run: |-
          sudo --preserve-env ./build.py ${{ env.JELLYFIN_VERSION }} docker

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Debug: List Docker images"
        run: docker images

      - name: Push to Docker Hub
        run: |
          echo "Attempting to tag and push image with version: ${{ env.JELLYFIN_VERSION }}"
          if docker image inspect ${{ secrets.DOCKER_USERNAME }}/jellyfin_with_request:${{ env.JELLYFIN_VERSION }} &> /dev/null; then
            echo "Tagging image..."
            docker tag ${{ secrets.DOCKER_USERNAME }}/jellyfin_with_request:${{ env.JELLYFIN_VERSION }} ${{ secrets.DOCKER_USERNAME }}/jellyfin_with_request:${{ env.JELLYFIN_VERSION }}
            echo "Pushing image..."
            docker push ${{ secrets.DOCKER_USERNAME }}/jellyfin_with_request:${{ env.JELLYFIN_VERSION }}
          else
            echo "Error: Docker image ${{ secrets.DOCKER_USERNAME }}/jellyfin_with_request:${{ env.JELLYFIN_VERSION }} not found"
            echo "Available images:"
            docker images
            exit 1
          fi

      - name: Discord notification
        if: failure()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: The workflow "Release Build and Push to DockerHub" has failed! Check the logs for more information. Input version - ${{ inputs.version || 'master' }}, Set JELLYFIN_VERSION - ${{ env.JELLYFIN_VERSION }}
          
