name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 1 * * *'  # Runs at midnight EST every day
  workflow_dispatch:      # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/jellyfin/jellyfin-packaging.git
          
      - name: Fetch all
        run: |
          git fetch origin
          git fetch upstream
          
      - name: Sync with upstream
        id: sync
        continue-on-error: true
        run: |
          git checkout master
          if ! git merge upstream/master; then
            git merge --abort
            echo "MERGE_FAILED=true" >> $GITHUB_ENV
            exit 1
          fi
      - name: Push changes
        if: steps.sync.outcome == 'success'
        run: git push origin master

      - name: Send Discord notification on failure
        if: env.MERGE_FAILED == 'true'
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: '🚨 Merge failed in jellyfin-packaging fork sync! Manual intervention required.'
