name: "Unstable Build"

on:
  schedule:
    # Weekly unstable trigger on Monday at 05:00 GMT
    - cron: '0 5 * * 1'
  workflow_dispatch:
    # Manual trigger

env:
  SDK_VERSION: "9.0.x"

permissions:
  contents: read

jobs:
  Docker:
    runs-on: ubuntu-24.04
    continue-on-error: false  # true in prod, false for testing
    steps:
      - name: "Set dated version for unstable builds"
        id: version
        run: |-
          echo "JELLYFIN_VERSION=$(date +'%Y%m%d%H')" >> $GITHUB_ENV
          echo "JELLYFIN_RELEASE_TYPE=unstable" >> $GITHUB_ENV
          echo "DEBUG_FLAG=--debug" >>$GITHUB_ENV

      - name: "Install dependencies"
        run: |-
          sudo apt-get update
          sudo apt-get install --yes python3-git python3-yaml

      - name: "Checkout repository"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: "Prepare repository"
        run: |-
          ./checkout.py master

      - name: "Run builder for Docker containers"
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
        run: |-
          sudo --preserve-env ./build.py ${{ env.JELLYFIN_VERSION }} docker ${{ env.DEBUG_FLAG }}

  Nuget:
    runs-on: ubuntu-24.04
    steps:
      - name: "Set dated version for unstable builds"
        id: version
        run: |-
          echo "JELLYFIN_VERSION=$(date +'%Y%m%d%H')" >> $GITHUB_ENV
          echo "JELLYFIN_RELEASE_TYPE=unstable" >> $GITHUB_ENV
          echo "DEBUG_FLAG=--debug" >>$GITHUB_ENV

      - name: "Install dependencies"
        run: |-
          sudo apt-get update
          sudo apt-get install --yes python3-git python3-yaml

      - name: "Setup .NET"
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
        with:
          dotnet-version: ${{ env.SDK_VERSION }}

      - name: "Checkout repository"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: "Prepare repository"
        run: |-
          ./checkout.py master

      - name: "Run builder for Nuget"
        env:
          NUGET_STABLE_KEY: ${{ secrets.NUGET_STABLE_KEY }}
          NUGET_UNSTABLE_KEY: ${{ secrets.NUGET_UNSTABLE_KEY }}
        run: |-
          ./build.py ${{ env.JELLYFIN_VERSION }} nuget
